insert into `ac_category` (`id`, `category`) values('1','Action Bars');
insert into `ac_category` (`id`, `category`) values('2','Chat & Communication');
insert into `ac_category` (`id`, `category`) values('3','Artwork');
insert into `ac_category` (`id`, `category`) values('4','Auction & Economy');
insert into `ac_category` (`id`, `category`) values('5','Audio & Video');
insert into `ac_category` (`id`, `category`) values('6','Bags & Inventory');
insert into `ac_category` (`id`, `category`) values('7','Boss Encounters');
insert into `ac_category` (`id`, `category`) values('8','Buffs & Debuffs');
insert into `ac_category` (`id`, `category`) values('9','Class');
insert into `ac_category` (`id`, `category`) values('10','Combat');
insert into `ac_category` (`id`, `category`) values('11','Guild');
insert into `ac_category` (`id`, `category`) values('12','Mail');
insert into `ac_category` (`id`, `category`) values('13','Map & Minimap');
insert into `ac_category` (`id`, `category`) values('14','Minigames');
insert into `ac_category` (`id`, `category`) values('15','Miscellaneous');
insert into `ac_category` (`id`, `category`) values('16','Professions');
insert into `ac_category` (`id`, `category`) values('17','PvP');
insert into `ac_category` (`id`, `category`) values('18','Quests & Leveling');
insert into `ac_category` (`id`, `category`) values('19','Roleplay');
insert into `ac_category` (`id`, `category`) values('20','Tooltip');
insert into `ac_category` (`id`, `category`) values('21','Unitframes');
